### ISSUE TITLE
When are you going to release your code？

### ISSUE THREAD

**Issue by longmalongma** [svip-lab/IVOS-W#1]
Hi, thanks for your great. When are you going to release your code？

**Comment by bertjiazheng** [comment]
Hi @longmalongma ,

Thanks for your interest in our work. We are currently working on rectifying the code and will release the code in the next few weeks.

Best,
Jia

**Comment by bertjiazheng** [comment]
Hi, @longmalongma 

Sorry for the late reply. We have released our code and trained models. 

Best,
Jia
